#!/bin/bash

source ~/anaconda3/etc/profile.d/conda.sh
conda activate
python /Applications/Jupyter.app/Contents/MacOS/clean.py

echo "Enter p for Python, s for Sage"
read choice

if [ $choice == "s" ]; then
conda activate sage
FILE=/Users/onno/Projects/stuff/`date +%F`-sage.ipynb

if [ ! -f $FILE ]; then
cat > $FILE << EOF
{
"cells": [
{
"cell_type": "code",
"execution_count": null,
"metadata": {},
"outputs": [],
"source": [
    "# Config\n",
    "%display latex\n",
    "plot.options['dpi'] = 200\n",
    "plot.options['figsize'] = (12, 8)"
]
}
],
"metadata": {},
"nbformat": 4,
"nbformat_minor": 2
}
EOF
fi

sage -n jupyter --MappingKernelManager.default_kernel_name='sagemath' $FILE

else
FILE=/Users/onno/Projects/stuff/`date +%F`.ipynb

if [ ! -f $FILE ]; then
cat > $FILE << EOF
{
"cells": [
{
"cell_type": "code",
"execution_count": null,
"metadata": {},
"outputs": [],
"source": [
    "import numpy as np\n",
    "import matplotlib as mpl\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns"
]
},
{
"cell_type": "code",
"execution_count": null,
"metadata": {},
"outputs": [],
"source": [
    "# Matplotlib configuration\n",
    "%config InlineBackend.figure_format = 'retina'\n",
    "mpl.rc('figure', figsize=(8, 6), dpi=100)\n",
    "sns.set()"
]
}
],
"metadata": {},
"nbformat": 4,
"nbformat_minor": 2
}
EOF
fi

jupyter-notebook $FILE   #--notebook-dir /Volumes/Data
fi
