#!/bin/bash

FILE=/Users/onno/Projects/stuff/`date +%F`.ipynb

python /Applications/Jupyter.app/Contents/MacOS/clean.py

if [ ! -f $FILE ]
then
cat > $FILE << EOF
{
"cells": [],
"metadata": {},
"nbformat": 4,
"nbformat_minor": 2
}
EOF
fi

/Users/onno/anaconda3/bin/jupyter-notebook $FILE   #--notebook-dir /Volumes/Data
bash
