#!/bin/bash

source ~/anaconda3/etc/profile.d/conda.sh
conda activate
python /Applications/Jupyter.app/Contents/MacOS/clean.py

echo "Enter p for Python, s for Sage"
read choice

if [ $choice == "s" ]
then
conda activate sage
FILE=/Users/onno/Projects/stuff/`date +%F`-sage.ipynb
else
FILE=/Users/onno/Projects/stuff/`date +%F`.ipynb
fi

if [ ! -f $FILE ]
then
cat > $FILE << EOF
{
"cells": [],
"metadata": {},
"nbformat": 4,
"nbformat_minor": 2
}
EOF
fi

if [ $choice == "s" ]
then
sage -n jupyter $FILE
else
jupyter-notebook $FILE   #--notebook-dir /Volumes/Data
fi

bash
